CREATE DATABASE ACTIVIDAD1;
USE ACTIVIDAD1

CREATE TABLE MUSICOS(
    ID_MUSICO INT NOT NULL PRIMARY KEY CHECK(ID_MUSICO >0),
    NOMBRE VARCHAR(30) NOT NULL, 
    APELLIDO VARCHAR(30) NOT NULL, 
    FECHAINGRESO DATE NOT NULL,
    FECHANAC DATE NOT NULL
);

CREATE TABLE TIPO_INSTRUMENTOS(
    ID_TIPO INT NOT NULL PRIMARY KEY,
    DESCRIPCION VARCHAR(20) NOT NULL
);

CREATE TABLE INSTRUMENTOS(
    COD_INSTRUMENTO NVARCHAR(10) NOT NULL,
    NOMBRE_INSTRUMENTO NVARCHAR(50) NOT NULL,
    ID_TIPO INT NOT NULL,
    PRIMARY KEY(COD_INSTRUMENTO),
    FOREIGN KEY (ID_TIPO) REFERENCES TIPO_INSTRUMENTOS(ID_TIPO)
);

CREATE TABLE MUSICO_INSTRUMENTOS( 
    ID_MUSICO INT NOT NULL CHECK(ID_MUSICO >0),
    COD_INSTRUMENTO NVARCHAR(10)NOT NULL,
    PRIMARY KEY (ID_MUSICO, COD_INSTRUMENTO),
    FOREIGN KEY (ID_MUSICO) REFERENCES MUSICOS(ID_MUSICO),
    FOREIGN KEY (COD_INSTRUMENTO) REFERENCES INSTRUMENTOS(COD_INSTRUMENTO)
);