CREATE DATABASE TORNEO_PESCA;

USE TORNEO_PESCA;

CREATE TABLE PARTICIPANTES (
    ID_PARTICIPANTE INT NOT NULL PRIMARY KEY,
    NOMBRE VARCHAR(20) NOT NULL,
    APELLIDO VARCHAR(20) NOT NULL,
    FECHA_NAC DATE NOT NULL,
    PAIS_NAC VARCHAR(20) NOT NULL,
);

CREATE TABLE TORNEOS (
    ID_TORNEO INT NOT NULL PRIMARY KEY,
    NOMBRE_TORNEO VARCHAR(20) NOT NULL,
    PREMIO INT NOT NULL,
    COSTO INT NOT NULL,
    CIUDAD VARCHAR(20) NOT NULL,
    PAIS VARCHAR(20) NOT NULL,
    FECHA_TORNEO DATE NOT NULL
);

CREATE TABLE ESPECIES_AUTORIZADAS (
    ID_TORNEO INT NOT NULL,
    ESPECIE VARCHAR(30) NOT NULL,
    FOREIGN KEY (ID_TORNEO) REFERENCES TORNEOS (ID_TORNEO)
);

CREATE TABLE PARTICIPANTES_X_TORNEOS (
    ID_INSCRIPCION INT NOT NULL PRIMARY KEY,
    ID_PARTICIPANTE INT NOT NULL,
    ID_TORNEO INT NOT NULL,
    FECHA_INSCRIPCION DATE NOT NULL,
    FOREIGN KEY (ID_PARTICIPANTE) REFERENCES PARTICIPANTES (ID_PARTICIPANTE),
    FOREIGN KEY (ID_TORNEO) REFERENCES TORNEOS (ID_TORNEO)
);

CREATE TABLE CAPTURAS (
    ID_CAPTURA INT NOT NULL PRIMARY KEY,
    ID_TORNEO INT NOT NULL,
    ID_PARTICIPANTE INT NOT NULL,
    ESPECIE VARCHAR(20) NOT NULL,
    PESO INT NOT NULL,
    HORA DATETIME NOT NULL,
    TAG_ID INT NOT NULL UNIQUE,
    FOREIGN KEY (ID_PARTICIPANTE) REFERENCES PARTICIPANTES (ID_PARTICIPANTE),
    FOREIGN KEY (ID_TORNEO) REFERENCES TORNEOS (ID_TORNEO)
);

CREATE TABLE GANADORES (
    ID_GANADOR INT NOT NULL PRIMARY KEY,
    ID_PARTICIPANTE INT NOT NULL,
    ID_TORNEO INT NOT NULL,
    FOREIGN KEY (ID_PARTICIPANTE) REFERENCES PARTICIPANTES (ID_PARTICIPANTE),
    FOREIGN KEY (ID_TORNEO) REFERENCES TORNEOS (ID_TORNEO)
);