-- 1 Los nombres y extensiones y tamaño en Megabytes de los archivos que pesen más que el promedio de archivos.
-- 2 Los usuarios indicando apellido y nombre que no sean dueños de ningún archivo con extensión 'zip'.
-- 3 Los usuarios indicando IDUsuario, apellido, nombre y tipo de usuario que no hayan creado ni modificado ningún archivo en el año actual.
-- 4 Los tipos de usuario que no registren usuario con archivos eliminados.
-- 5 Los tipos de archivos que no se hayan compartido con el permiso de 'Lectura'
-- 6 Los nombres y extensiones de los archivos que tengan un tamaño mayor al del archivo con extensión 'xls' más grande.
-- 7 Los nombres y extensiones de los archivos que tengan un tamaño mayor al del archivo con extensión 'zip' más pequeño.
-- 8 Por cada tipo de archivo indicar el tipo y la cantidad de archivos eliminados y la cantidad de archivos no eliminados.
-- 9 Por cada usuario indicar el IDUsuario, el apellido, el nombre, la cantidad de archivos pequeños (menos de 20MB) y la cantidad de archivos grandes (20MBs o más)
-- 10 Por cada usuario indicar el IDUsuario, el apellido, el nombre y la cantidad de archivos creados en el año 2022, la cantidad en el año 2023 y la cantidad creados en el 2024.
-- 11 Los archivos que fueron compartidos con permiso de 'Comentario' pero no con permiso de 'Lectura'
-- 12 Los tipos de archivos que registran más archivos eliminados que no eliminados.
-- 13 Los usuario que registren más archivos pequeños que archivos grandes (pero que al menos registren un archivo de cada uno)
-- 14 Los usuarios que hayan creado más archivos en el 2022 que en el 2023 y en el 2023 que en el 2024.